language: r
sudo: false
cache: packages
dist: trusty
r:
  - release

addons:
  apt:
    packages:
      - libgsl0-dev

env:
  global:
    - _R_CHECK_TIMINGS_=0
    - _R_CHECK_FORCE_SUGGESTS_=0  # no error if suggested packs are not avail
    - _R_CHECK_TESTS_NLINES_=999

warnings_are_errors: true
r_check_args: "--as-cran --run-donttest"

r_github_packages:
  - berndbischl/BBmisc
## The following will return when my PRs are merged
#  - berndbischl/ParamHelpers
  - mlr-org/mlr
  - jimhester/lintr
  - mb706/covr

before_install:
  # we want to see libpaths and installed packages from cache
  - Rscript -e 'message("LIBPATHS:"); .libPaths()'
  - Rscript -e 'message("INSTALLED PACKS:"); installed.packages()[,1:3]'

before_script:
  - rm inst/doc/*.*
  - Rscript -e 'install.packages("roxygen2")'
  - Rscript -e 'devtools::install_github("berndbischl/ParamHelpers", ref = "paramSetSugar")'
  - R --no-save <<< 'library("devtools"); document()'

script:
  - R CMD build .
  - travis_wait 100 R CMD check mlrCPO*.tar.gz --as-cran --run-donttest
  - grep -q -R "WARNING" "mlrCPO.Rcheck/00check.log" ; [ $? -ne 0 ]

after_success:
  - travis_wait 100 Rscript -e 'library(BBmisc);covr::codecov(quiet=FALSE)'
  - git checkout master
  - "export TRAVIS_COMMIT_MSG=\"$(git log --format=%B --no-merges -n 1)\""
  - R --no-save <<< 'library("devtools"); document(); build_vignettes();'
  - git config user.name $GN
  - git config user.email $GM
  - git config credential.helper "store --file=.git/credentials"
  - echo "https://${GITHUB_TOKEN}:@github.com" >> .git/credentials
  - git config push.default matching
  - git difftool -yx "diff -qI '20[0-9][0-9]-[0-9][0-9]-[0-9][0-9]\\|environment: 0x'" | grep 'and inst/doc' | sed -e 's|.*and inst/doc|inst/doc|' -e 's/ differ$//' | xargs git add
  - git add --force man/*
  - git add DESCRIPTION NAMESPACE
  - git commit -m "update auto-generated documentation [ci skip]" || true
  - git push

after_failure:
  - ./travis-tool.sh dump_logs

on_success: change
on_failure: always

notifications:
  email: false
